---
resources:
- name: source-code
  type: git
  source: 
    uri: https://github.com/mostrovoi/demo-canigo.git
    branch: master

jobs:
- name: job-demo-canigo
  public: true
  serial: true
  plan: 
   - get: source-code
     trigger: true
   - task: package
     privileged: true
     file: source-code/tasks/package.yml
