platform: linux

image_resource:
  type: docker-image
  source:
    repository: node
    tag: '8.4.0'

inputs:
  - name: sonar-runner

run:
  path: node
  args:
  - -e
  - "const projectStatus = require('./qualitygate_project_status.json'); if (projectStatus.status !== 'OK') { console.error('Quality gate goals missed. :-('); process.exit(1); }"
  dir: sonar-runner