apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: postgres
  namespace: dev
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
      - name: postgres
        image: gencatcloud/postgres:9.5
        imagePullPolicy: "Always"
        ports:
        - containerPort: 5432
        env:
        - name: POSTGRES_USER
          value: demospringboot
        - name: POSTGRES_PASSWORD
          value: password
        - name: PGDATA
          value: /var/lib/postgresql/data/pgdata
        volumeMounts:
        - mountPath: /var/lib/postgresql/data
          name: demo-canigo-postgredb
      volumes:
      - name: demo-canigo-postgredb
        persistentVolumeClaim:
           claimName: demo-canigo-pvc

