apiVersion: v1
kind: Service
metadata:
  labels:
    app: demo-canigo
  name: demo-canigo
  namespace: dev
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: demo-canigo
  type: ClusterIP
