apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  annotations:
    volume.alpha.kubernetes.io/storage-class: default
    volume.beta.kubernetes.io/storage-provisioner: kubernetes.io/azure-disk
  labels:
    app: demo-canigo-postgres
  name: demo-canigo-pvc
  namespace: dev
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 3Gi
  storageClassName: default
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: demo-canigo
  namespace: dev
spec:
  replicas: 1
  template:
  metadata:
    labels:
     app: demo-canigo
  spec:
    containers:
    - name: demo-canigo
      image: gencat.azurecr.io/demo-canigo:latest
      imagePullPolicy: "IfNotPresent"
      ports:
      - containerPort: 80
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: demo-canigo-postgres
  namespace: dev
spec:
  replicas: 1
  template:
  metadata:
    labels:
     app: demo-canigo-postgres
  spec:
    containers:
    - name: demo-canigo-postgres
      image: gencatcloud/postgres:9.5.3
      imagePullPolicy: "IfNotPresent"
      ports:
      - containerPort: 5432
      env:
      - name: POSTGRES_USER
        value: demospringboot
      - name: POSTGRES_PASSWORD
        value: password
      - name: PGDATA
        value: /var/lib/postgresql/data/pgdata
      volumeMounts:
        - mountPath: /var/lib/postgresql/data
          name: demo-canigo-postgredb
    volumes:
      - name: demo-canigo-postgredb
        persistentVolumeClaim:
          claimName: demo-canigo-pvc
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: demo-canigo-postgres
  name: demo-canigo-postgres
  namespace: dev
spec:
  ports:
  - name: postgresql
    port: 5432
    protocol: TCP
    targetPort: postgresql
  selector:
    app: demo-canigo-postgres
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: demo-canigo
  name: demo-canigo
  namespace: dev
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: demo-canigo
  type: ClusterIP
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  generation: 1
  name: demo-canigo
  namespace: dev
spec:
  rules:
  - host: bookstore.dev.matxa.es
    http:
      paths:
      - backend:
          serviceName: demo-canigo
          servicePort: 80
